# Generated by Django 4.2.6 on 2023-12-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=150)),
                ('salary', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
